# Generated by Django 4.0 on 2021-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_name_remove_comment_post_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
