# Generated by Django 4.0 on 2021-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_sitename_link_title_logoimage_title_social_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avdvertisementbanner',
            options={'verbose_name': 'Advertisement (Ads)', 'verbose_name_plural': 'Advertisement (Ads)'},
        ),
        migrations.AddField(
            model_name='avdvertisementbanner',
            name='where_to_locate',
            field=models.CharField(choices=[('Top Banner', 'Top Banner'), ('On side', 'On side')], max_length=12, null=True),
        ),
    ]
