# Generated by Django 4.0 on 2021-12-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_alter_avdvertisementbanner_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvdvertisementBanner',
            new_name='AdvertisementBanner',
        ),
    ]
