# Generated by Django 4.0 on 2021-12-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_rename_avdvertisementbanner_advertisementbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoimage',
            name='title',
        ),
        migrations.AddField(
            model_name='logoimage',
            name='brandlogo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
