# Generated by Django 4.0 on 2021-12-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_remove_logoimage_title_logoimage_brandlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoimage',
            name='url',
        ),
    ]
