# Generated by Django 4.0 on 2021-12-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlemedia_title_articlerating_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='title',
            new_name='message',
        ),
    ]
