# Generated by Django 4.0 on 2021-12-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articles_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='comment',
        ),
    ]
