# Generated by Django 4.0 on 2021-12-27 13:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('blog', '0007_articles_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='comment',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('body', ckeditor.fields.RichTextField()),
                ('website', models.URLField(blank=True)),
                ('created_time', models.DateTimeField()),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.customuser')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
