# Generated by Django 4.0 on 2021-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingarticle',
            name='make_this_top',
            field=models.CharField(choices=[('List', 'List'), ('Top', 'Top')], default='List', max_length=10, null=True),
        ),
    ]
