# Generated by Django 4.0 on 2021-12-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_trendingarticle_make_this_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingarticle',
            old_name='Articles',
            new_name='articles',
        ),
    ]
