# Generated by Django 4.0 on 2021-12-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_articles_trendingarticle_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingarticle',
            old_name='make_this_top',
            new_name='status_choice',
        ),
    ]
