# Generated by Django 4.0 on 2021-12-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_make_this_top_trendingarticle_status_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyarticle',
            old_name='Articles',
            new_name='articles',
        ),
        migrations.AlterField(
            model_name='trendingarticle',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treding_post', to='blog.articles'),
        ),
    ]
