# Generated by Django 4.0 on 2021-12-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_articles_weeklyarticle_articles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
            ],
            options={
                'verbose_name_plural': 'Recent Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
